name: C++ CI

on:
  push:
    branches:
      - speedup
  pull_request:
    branches:
      - speedup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: speedup

    - name: install dependencies
      run: sudo apt install -y zlib1g:

    - name: Build
      working-directory: src/
      run: make -f Makefile_linux

    - name: Test
      working-directory: src/
      run: ./selscan
